insert into project (id, title) values ('NCA-123-1', 'Employee Events');
insert into project (id, title) values ('NCA-123-2', 'Girders iOS');
insert into project (id, title) values ('NCA-123-3', 'Android Infrastructure');
insert into project (id, title) values ('NCA-123-4', 'Buildcrew');
insert into project (id, title) values ('NCA-123-5', 'Surplus Capacity');
insert into project (id, title) values ('NCA-123-6', 'Availability');
insert into project (id, title) values ('NCA-123-7', 'Project Management Office (PMO)');
insert into project (id, title) values ('NCA-123-8', 'Line Management');
insert into project (id, title) values ('NCA-123-9', 'Website Maintenance');
insert into project (id, title) values ('NCA-123-0', 'User Experience Office (UXO)');
