insert into project (id, title) values ('NCA-029-0', 'Employee Events');
insert into project (id, title) values ('NCA-312-2', 'Girders iOS');
insert into project (id, title) values ('NCA-356-1', 'Android Infrastructure');
insert into project (id, title) values ('NCA-301-5', 'Buildcrew');
insert into project (id, title) values ('NCA-400-9', 'Surplus Capacity');
insert into project (id, title) values ('NCA-056-3', 'Availability');
insert into project (id, title) values ('NCA-256-2', 'Project Management Office (PMO)');
insert into project (id, title) values ('NCA-090-7', 'Line Management');
insert into project (id, title) values ('NCA-096-2', 'Website Maintenance');
insert into project (id, title) values ('NCA-347-0', 'User Experience Office (UXO)');
